### ISSUE TITLE
meal access needed for on-site renters group

### ISSUE THREAD

**Issue by stonylohr** [jkimdon/cohotikimeals#1]
Being a member of the "on-site renters" group apparently does not allow access to the meal pages in the software, and should. The current work-around is to assign renters to the Owners group.

**Comment by jhilkey** [comment]
@stonylohr @jkimdon Do you know who I could test this with?

**Comment by jkimdon** [comment]
I think this is now working after a permissions change. Carolyn verified she can access the meals.
