### ISSUE TITLE
make it more clear that meal name is link to details

### ISSUE THREAD

**Issue by stonylohr** [jkimdon/cohotikimeals#10]
In the initial meal summary screen that shows up when you click a meal in the calendar, the meal's name (usually "Community Meal") is a link to the meal's details page. For many users, this hasn't proven intuitive. We should do something to draw attention to it as something interactive, likely with some explicit mention of "click for details" or something.

**Comment by jkimdon** [comment]
Just put a button under the meal name for now

**Comment by jkimdon** [comment]
Added a button. 9fbe3549f95387c4bfcfb08a59d392dee320aeef and 5fa6cad0dae993efeaad9456dabe5c89c5d7d4c1
