### ISSUE TITLE
remove Alana and Ciera from recurring meals

### ISSUE THREAD

**Issue by jhilkey** [jkimdon/cohotikimeals#117]
I'm not sure how to do this. I got this:
select * from cohomeals_participant_recurrence where userId in ('ahilkey', 'cahilkey');
but I don't know if this would do it:
delete from cohomeals_participant_recurrence where userId in ('ahilkey', 'cahilkey');

**Comment by jhilkey** [comment]
@stonylohr would this do it?
delete from cohomeals_participant_recurrence where userId in ('ahilkey', 'cahilkey');

**Comment by stonylohr** [comment]
Yes, your proposed delete statement would be the approach I would take. I don't think there's a way to just deactivate auto-signups, so I think they have to be deleted.

**Comment by jhilkey** [comment]
done
