### ISSUE TITLE
Stony no longer sees user admin tab in software

### ISSUE THREAD

**Issue by stonylohr** [jkimdon/cohotikimeals#127]
I'm not sure if it's a change to my account, or if maybe the functionality has just been relocated or something, but it would be handy to have back.

**Comment by jkimdon** [comment]
I believe I have restored it. Did you lose anything else? @stonylohr

**Comment by stonylohr** [comment]
I see it again. I didn't notice any other loss of admin ability, aside from the cancel button failing, as noted in its separate issue. Thanks!
