### ISSUE TITLE
Cancel button fails for Thu 2020/02/06 meal

### ISSUE THREAD

**Issue by stonylohr** [jkimdon/cohotikimeals#128]
No head chef, and only about a week away. I get a blank white screen when I press the button, and the meal isn't cancelled.

Meal link: https://tiki.cohoecovillage.org/coho_meals-view_entry.php?id=3069&mealdatetime=1581040800

Setting priority to high, to encourage us to deal with it before the meal arrives. If you can't get to it by 1/5, you can bounce it back to me, and I can cancel it through a db update query.

**Comment by jkimdon** [comment]
Thanks for finding this. It was a careless commenting error on my part. Fixed and I canceled the meal. Fixed with commit #b2e985ff73f4c9a08c03539b81d228f881d84221
