### ISSUE TITLE
prepaid text change

### ISSUE THREAD

**Issue by stonylohr** [jkimdon/cohotikimeals#134]
From April:
I do have a request for you to edit text on the meal report. Where it says:
"How much did you spend using Farmers' Market Cards?”
Change it to read:
How much did you spend using Market Cards and Prepaid Accounts? (i.e. Denison’s, Gathering Together, Rainshine, Round House Farm, Wild Yeast Bakery)

I think one entry field will suffice. We’ll have a chefs' night in in February to show this change. I’ll send an explanatory email as soon as  you get it done.

**Comment by stonylohr** [comment]
I'm setting the priority to high, simply because April is hoping to include the change in things explained during the upcoming chefs night in. I'm not sure we have a specific date, and it also sounds like it doesn't have to be done before the chefs night in, as long as it's done fairly soon after.

**Comment by jkimdon** [comment]
done with commit 065b7e04135cbaf130c03f93238c465531e88342
