### ISSUE TITLE
fix CoHo Day meal id 3115

### ISSUE THREAD

**Issue by stonylohr** [jkimdon/cohotikimeals#151]
In the calendar view, this meal shows as being on Sunday 2021/03/21, but in the summary and detail views, it shows as 6am 3/22. 
The desired time is 12:30pm 3/21.

Link: https://tiki.cohoecovillage.org/coho_meals-view_entry.php?id=3115&mealdatetime=1616418000

**Comment by stonylohr** [comment]
Update from Carrie:
At one point it let me add the day and time but didn't save it..
Then it let me add some helpers but then stopped and went to a blank page...

**Comment by jkimdon** [comment]
Fixed an am/pm issue in the meal editing handler. Commit 2e0c11677048acde7e07373d10282691cfdb514c
