### ISSUE TITLE
Adding all retreat meals

### ISSUE THREAD

**Issue by jkimdon** [jkimdon/cohotikimeals#23]
saturday lunch: anne
Saturday dinner: stony (already done)
sunday breakfast: jeremy
sunday lunch: jane

**Comment by stonylohr** [comment]
Getting close. I've added the meals, but want to confirm that I got the info right, and still need to add non-chef crew slots. I hope to finish tomorrow. May send announcement email tonight.

**Comment by stonylohr** [comment]
Added crew slots and sent announcement.
