### ISSUE TITLE
Nic shows up twice in the list of meal program members

### ISSUE THREAD

**Issue by jkimdon** [jkimdon/cohotikimeals#36]

**Comment by stonylohr** [comment]
Also Sabine, Seraina, and Ted. Quite possibly others. Those are just people I noticed while signing up right now. Feels like maybe non-owner families?

**Comment by stonylohr** [comment]
Also make sure he hasn't been getting charged twice

**Comment by jkimdon** [comment]
I think it is because they are members of both "onsite renters" and "owners". Recall we put people into the owners category temporarily because the renters wasn't working

**Comment by jkimdon** [comment]
I changed preferences so it appears renters is now working, so I removed the renters from the owners list, so the double appearances seem to be fixed.
