### ISSUE TITLE
placeholder: add teatime support

### ISSUE THREAD

**Issue by stonylohr** [jkimdon/cohotikimeals#5]
It sounds like the teatime meals could use some meal software help. There are likely a few different ways we could approach this, and I'm not going to try to spell out a single strategy here. We can replace this with one or more specific issue items later if needed.

**Comment by jkimdon** [comment]
Add it as a recurring meal in the database

**Comment by jhilkey** [comment]
Is this a duplicate of #33 ?

**Comment by stonylohr** [comment]
I've added meal recurrences, and of course walk-ins are no longer charged extra. I think that may be everything needed for this ticket.
