### ISSUE TITLE
enhancement: tiki behavior when not logged in

### ISSUE THREAD

**Issue by stonylohr** [jkimdon/cohotikimeals#6]
It would be more user-friendly for the tiki to prompt for login on pages that require it, rather than saying permission denied in those cases, especially since the current login link is easy to overlook.

**Comment by jhilkey** [comment]
Fixed so when a user is not logged in and attempts to access a tiki page they will be sent to a page with a login box - General / Navigation / Redirects : On permission denied, display login module (enabled)
