### ISSUE TITLE
Jane possibly charged twice for same meal

### ISSUE THREAD

**Issue by stonylohr** [jkimdon/cohotikimeals#97]
From Jane:
I was charged on Dec 7, 2018 for a meal - 3.50.  I just got charged again for same meal, (Hanukkah dinner) 5.50. 

Investigate whether charges on her account look legit, and maybe try to fit a pattern to any issues spotted, to help track down the cause.

**Comment by jkimdon** [comment]
I couldn't find the double charge. I responded to Jane with the following email to request more information:

Hi Jane,

I see the charge for the Dec 7, 2018 Hannukah meal of $5.50, but I can't find any other charge for that day. The closest I've found is from the previous year Dec 7, 2017 for $3.50. Can you help me find the issue you were referring to?

Thanks,
Joey

**Comment by jkimdon** [comment]
Received email confirming she hadn't noticed the year.
